### ISSUE TITLE
How can I embed this in my Android project?

### ISSUE THREAD

**Issue by jd-alexander** [DwayneSamuels/emotion-emoji#3]
Is there a way I can pull this into Android, eg. in a `TextView`?

**Comment by DwayneSamuels** [comment]
Hi Joel, thanks for your question. I didn't know Jamaica had Android developers.

I think that's possible but we would have to conduct a study to understand how Jamaicans use emojis for it to fit your context. 

If you have any other suggestions or would love to start your own Emotion-Emoji fork for Jamaica, please feel free to do so!

- D
